### ISSUE TITLE
frps正常启动 fpc客户端连接报错（send Login request to plugin error） 版本0.33.0

### ISSUE THREAD

**Issue by xhiscl** [fatedier/frp#1785]

**Comment by fatedier** [comment]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**


**What operating system and processor architecture are you using (`go env`)?**


**Configures you used:**


**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional information you deem important (e.g. issue happens only occasionally):**


**Can you point out what caused this issue (optional)**

**Comment by UnknowViewer** [comment]
遇到相同问题，现已修复。

## [软件运行命令]
- Server-side
```
./frps -c frps_full.ini
```
- Client-side
```
./frpc -c frpc_full.ini 
-OR-
./frpc -c frpc.ini 
```

## [问题原因]
如果在服务器端运行时选择`frps_full.ini`，又没有安装相关插件 (Dashboard) 的话，虽然服务器端能启动，但是客户端连接时会报 **send Login request to plugin error**

## [如何解决]
在服务器端运行时选择 `frpc.ini` **而不是** `frpc_full.ini`
```
./frps -c frps.ini
```

-------
🇬🇧 in English
Met the same issue but fixed.

## [What I run]
- Server-side
```
./frps -c frps_full.ini
```
- Client-side
```
./frpc -c frpc_full.ini 
-OR-
./frpc -c frpc.ini 
```

## [Root cause]
The target configuration file is `frps_full.ini` while running FRP in the server. There are some plugin configs in `frps_full.ini`, although FRP can be started in server with this full configuration, but it'll return **send Login request to plugin error** if you started FRP client

## [How to fix]
Select `frps.ini` as configuration file instead of `frps_full.ini` while running the FRP
```
./frps -c frps.ini
```

>> EOF

**Comment by touchmii** [comment]
把frps full ini文件末尾的两个插件注释掉就可以了，这两个插件表示用外部服务器来给用户授权，所以才会提示登陆失败。

**Comment by weifeng12x** [comment]
> 把frps full ini文件末尾的两个插件注释掉就可以了，这两个插件表示用外部服务器来给用户授权，所以才会提示登陆失败。

无语了，照着官方教程配置，最后发现是这个问题。最后那个服务器插件配置文件能默认注释掉吗? 谢谢。 @fatedier

**Comment by fatedier** [comment]
@weifeng12x 文档里那么多可用的示例不看，full example 文件是一个尽量包含所有配置的示例文件，不是拿来直接用的。

我会考虑在这个文件里加上确保无法正常运行的配置项，以免再有用户用这个文件直接运行不看文档而导致产生各种奇怪的问题。

**Comment by weifeng12x** [comment]
> @weifeng12x 文档里那么多可用的示例不看，full example 文件是一个尽量包含所有配置的示例文件，不是拿来直接用的。
> 
> 我会考虑在这个文件里加上确保无法正常运行的配置项，以免再有用户用这个文件直接运行不看文档而导致产生各种奇怪的问题。

事实上我是照着这个界面操作的最新版
https://gofrp.org/zh-cn/docs/setup/

./frps -c ./frps.toml 这个默认的配置文件应该不是 full example吧

**Comment by fatedier** [comment]
@weifeng12x  恩，可能确实是有歧义，新的 release 版本里会删除这些示例配置文件，只提供可执行应用。

发现确实有很多人是直接拿这个文件来跑，完全不明白其中各种配置的含义，导致各种奇奇怪怪的问题。这个配置的本意是一个快捷查询一些参数写法的示例，而不是直接拿来运行的。
