### ISSUE TITLE
The token does not match after upgrading to version 0.36.2.

### ISSUE THREAD

**Issue by Dagsi** [fatedier/frp#2325]
**[REQUIRED] hat version of frp are you using** 

Version:v0.36.2

**[REQUIRED] What operating system and processor architecture are you using**
OS:linux_arm64
CPU architecture:

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. Stop the program
2. Replacement program
3. Re-run, and did not modify the configuration file, but the token does not match.

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by Dagsi** [comment]
log file echo:register control error: token in login doesn't match token from configuration

**Comment by bingtianbaihua** [comment]
what is the versions of your frpc and frps ?

**Comment by ViRb3** [comment]
I can confirm. The problem is that if you run `./frpc` or `./frps` without any arguments, it will execute in "cmd mode" instead of "ini mode". If you are in "cmd mode", the token is parsed as an argument from the command line, which in your case is empty. If you explicitly run `./frpc -c fprc.ini` or `./frps --config frps.ini`, then the correct "ini mode" will be selected, and connection succeeds. I suppose the token mismatch error happens because the client will enter "cmd mode" by default, while the server will enter "ini mode" by default, or vise versa. This is definitely an issue that needs to be cleared though, as it was quite confusing to debug, and a lot of people have the same problem across online forums.

**Comment by bingtianbaihua** [comment]
./frpc will use the default value  ./frpc.ini 
./frps without default file.

**Comment by ViRb3** [comment]
Right, so `./frpc` will run in "ini mode", parsing the token from the ini file, while `./frps` will run in "cmd mode", not parsing the token, and that's where you get a mismatch error.

**Comment by bingtianbaihua** [comment]
> Right, so `./frpc` will run in "ini mode", parsing the token from the ini file, while `./frps` will run in "cmd mode", not parsing the token, and that's where you get a mismatch error. These are two different default behaviors which is quite confusing in my opinion. Perhaps it's a good idea to make them both "ini by default" or "cmd by default"?

A good point.

**Comment by jjqtony** [comment]
I have the same problem even if frpc -c /etc/frpc.ini and frps -c /etc/frps.ini.  
The version of my frp is 0.36.2
