### ISSUE TITLE
我只能说frp的windows64客户端有很大的安全隐患。

### ISSUE THREAD

**Issue by Duldahar** [fatedier/frp#2343]
在Released页面下载的客户端，windows报木马。
结合之前部署FRP，windows10被中勒索病毒，我只能说大家谨慎。

网上也有很多FRP被中勒索病毒的案例，大家可以搜索下。

虽然是中病毒的机器本身是3389端口，但远程服务器上的2层路由器都做了端口转发。除了本身客户机的ipv6，被扫描到端口被暴力破解的途径，只能让人怀疑。

**Comment by BecodReyes** [comment]
https://github.com/fatedier/frp/issues/2095
一个连置顶都不看的人是**屑**

我只能说林子大了什么鸟都有
一个开源项目要是埋了木马病毒也就不会活到今天并且还有4w的star
putty不也是被当hacktool杀过？
**真正干坏事的不是这个东西，而是使用它的人**

**Comment by Duldahar** [comment]
我昨天下载了2次，frp_0.36.2_windows_amd64.zip，均提示：高风险：Trojan:Script/Oneeva.A!ml

**Comment by rampageX** [comment]
@Duldahar 你不是小白，我是说，你是白痴

**Comment by zqs01** [comment]
Windows客户端报病毒，服务器中过病毒+1

**Comment by andywang1011** [comment]
> 在Released页面下载的客户端，windows报木马。
> 结合之前部署FRP，windows10被中勒索病毒，我只能说大家谨慎。
> 
> 网上也有很多FRP被中勒索病毒的案例，大家可以搜索下。
> 
> 虽然是中病毒的机器本身是3389端口，但远程服务器上的2层路由器都做了端口转发。除了本身客户机的ipv6，被扫描到端口被暴力破解的途径，只能让人怀疑。

请善用STCP

**Comment by bingtianbaihua** [comment]
置顶的 issue 可以看下。

**Comment by c0mmit** [comment]
我在这里贴一下我遇到的问题，我也有过怀疑是不是存在漏洞或者什么
说开源项目有木马活不到今天的那个人也请注意一下，可能正因为开源导致你会完全信任它（不知道你有没有听过 `RVN 增发` 这个事件），事实上它开源了，但是谁在审查呢？反正你没。

好了说具体问题，我遇到的没有到勒索的程度，是正常运行了挺长时间之后才有的（之前一直没问题，但是后来哪怕重启，过一段时间也会复现）。版本似乎为 0.33 左右，情况是，持续性CPU占用100%，当然我无法提供任何可供修复的材料，并且对此也只是持有怀疑态度。将版本更新到 0.35.0 后，尚未遇到问题。

**Comment by bingtianbaihua** [comment]
> 我在这里贴一下我遇到的问题，我也有过怀疑是不是存在漏洞或者什么
> 说开源项目有木马活不到今天的那个人也请注意一下，可能正因为开源导致你会完全信任它（不知道你有没有听过 `RVN 增发` 这个事件），事实上它开源了，但是谁在审查呢？反正你没。
> 
> 好了说具体问题，我遇到的没有到勒索的程度，是正常运行了挺长时间之后才有的（之前一直没问题，但是后来哪怕重启，过一段时间也会复现）。版本似乎为 0.33 左右，情况是，持续性CPU占用100%，当然我无法提供任何可供修复的材料，并且对此也只是持有怀疑态度。将版本更新到 0.35.0 后，尚未遇到问题。



---
v0.32.0 以前包括 v0.32.0 ，有内存泄露问题，可能有一定的关系。 建议更新到 fix 之后的版本，可以关注 release 。

**Comment by feiker315** [comment]
我的服务器用了有1年了，开了3389没有任何问题，最近几天用了frp-windows64版，客户端报毒没理他，昨天服务器中了勒索病毒，内网主机也映射了3389，密码也被改了，差点也中毒，还好抢救的及时。我想说release里的exe程序上传到GitHub后是否安全。会不会GitHub不太靠谱。如果说3389被穷举密码，时间也太巧合了吧。而且这么短的时间，穷举内网密码是很难的。

**Comment by ksamwang** [comment]
就在刚刚服务器密码被篡改，大家谨慎，使用的是最新发行windows版本

**Comment by feiker315** [comment]
最好自己编译，我自己编译的就没有报病毒，但是从网上直接下载的就报病毒了，所以这个软件一定要自己编译。发自我的iPhone------------------ 原始邮件 ------------------发件人: Aluncca  ***@***.***>发送时间: 2025年5月18日 04:21收件人: fatedier/frp ***@***.***>抄送: feiker315 ***@***.***>, Comment ***@***.***>主题: Re: [fatedier/frp] 我只能说frp的windows64客户端有很大的安全隐患。 (#2343)
ksamwang left a comment (fatedier/frp#2343)
就在刚刚服务器密码被篡改，大家谨慎，使用的是最新发行windows版本

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/fatedier/frp/issues/2343#issuecomment-2888568731",
"url": "https://github.com/fatedier/frp/issues/2343#issuecomment-2888568731",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by onephp** [comment]
> 了3389没有任何问题，最近几

昨天我朋友中了勒索病毒的，frp是我推荐给他的，用来映射 3389端口。中毒后表现为 exe 都打不开，fprc.toml 被篡改成了乱码，所以windows版本的慎用，感觉问题很大。

**Comment by feiker315** [comment]
建议自己编译并检查源代码，我自己编译的没有报病毒。

**Comment by jeffpeng3** [comment]
看這樓搞抽象，笑死了

**Comment by yangjieshao** [comment]
首先，自用的话自己注意点别暴露敏感端口，加个白名单啥的问题不大
但是，凡事都有个但是
不是所有情况都可以去给杀毒软件加白名单的，特别是在公司内部用，白名单不是想加就能加的
所以这个问题还是得想办法解决

当然，作为用户，我最近在看其它几款内网穿透工具了
