### ISSUE TITLE
This is a command line tool.  You need to open cmd.exe and run it from there.

### ISSUE THREAD

**Issue by dellshan** [fatedier/frp#3584]
### Bug Description

This is a command line tool.

You need to open cmd.exe and run it from there.

### frpc Version

This is a command line tool.  You need to open cmd.exe and run it from there.

### frps Version

This is a command line tool.  You need to open cmd.exe and run it from there.

### System Architecture

This is a command line tool.  You need to open cmd.exe and run it from there.

### Configurations

This is a command line tool.

You need to open cmd.exe and run it from there.

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by vithusel** [comment]
There is literally no information to go off of here. 

If you are trying to run frp on a windows machine, server or normal client it needs to be run headless. Theres no gui interface. 

You can launch it by opening command prompt or powershell. Navigate to the directory where frp resides and type ./frpc.exe or ./frps.exe depending on what you are using. You will also need to configure the config file so the launch parameters would have -c whatevernotconfig.txt etc

**Comment by lss4** [comment]
This is not really a bug but certainly not friendly for especially Windows -- as even shortcuts configured with necessary arguments would not work because of this. I've run into this issue many times before.

The correct way to run frp in Windows is to create a bat/cmd file with the necessary arguments, then create a shortcut pointing to the bat/cmd with correct working directory, instead of the frp executable itself.

At least as of Windows 10 there's no option for shortcuts to make it "run in a terminal" like some Linux DEs.

**Comment by vithusel** [comment]
If really needed. Someone could wrap frp.exe with another exe with the launch parameters preconfigured.

**Comment by fimmspin** [comment]
You can set the shortcut to point to cmd.exe and execute the command:
cmd.exe /c "C:\frp-folder\frpc.exe -c frpc.ini"
