### ISSUE TITLE
[Feature Request] Auto retry on first connect.

### ISSUE THREAD

**Issue by pituluk** [fatedier/frp#3752]
### Describe the feature request

If the first connection fails FRP quits and doesnt retry, but if it loses connection after successful first connection it keeps retrying until it connects. It would be nice to have it keep retrying on first connection too for systems that might launch without access to internet yet.
"login to server failed: dial tcp x: connect: network is unreachable"

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
Decide if exit program when first login failed, otherwise continuous relogin to frps, default is true.
`loginFailExit = true`

I see that the author has corrected the error message to quickly locate this point (not yet released).
https://github.com/fatedier/frp/commit/184223cb2f240b844f90b3390645672d2225da88#diff-37135e06c87eb7f15648ee3df06d54a2a52cab735ea4110e81610945fe38f7d4R123-R125
