### ISSUE TITLE
Running OpenVPN Server behind NAT using frp

### ISSUE THREAD

**Issue by thinkpeach-ho** [fatedier/frp#3851]
### Bug Description

I am currently accessing the internal OpenVPN server through the port using frp.
But while checking the related logs of OpenVPN server .  I found that the client addresses of these logs were internal IP addresses, not client‘s  public IP addresses. 
I tried to using HAproxy between frp to OpenVPN , But it make me can't access OpenVPN via frp .
How should I do if I want to show the client's public IP address in the log?

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

CentOS Stream release 8

### Configurations

frpc.ini
[common]
server_addr = 192.168.101.15
server_port = 7000
token = NyFut8qo

[openvpn]
type = tcp
remote_port = 41194
local_port = 41194
local_ip = 192.168.100.10

frps.ini
[common]
bind_port = 7000
token = NyFut8qo
enable_prometheus = true

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by xqzr** [comment]
需要 OV 支持 `proxy protocol`
https://gofrp.org/zh-cn/docs/features/common/realip/#proxy-protocol

**Comment by thinkpeach-ho** [comment]
I tried it , but not work

**Comment by eebssk1** [comment]
> I tried it , but not work

That's means OpenVPN do not support that method. You should raise the issue to OpenVPN.
But I remember there IS a tool that works and uses linux tricks to turn internal IP to real IP,But I can not remember the name.

**Comment by testingnic** [comment]
Hello, I also tried to link this tunnel with ovpn but it was not possible.

@thinkpeach-ho 
@eebssk1 
@fatedier 


try
serverAddr="216.189.154.18"
serverPort = 80

[[proxies]]
name = "ovpn"
type = "tcp"
localIP="127.0.0.1"
localPort = 4545
remotePort = 2323


my configuration in ovpn is

remote 127.0.0.1 2323

route 216.189.154.18 255.255.255.255 net_gateway


I also tried using http as a listener with socks5 and http in ovpn so that the tunnel connection was achieved and the connection was not made either.

socks-proxy 127.0.0.1 6004
route 216.189.154.18 255.255.255.255 net_gateway


socks-proxy 127.0.0.1 6003
route 216.189.154.18 255.255.255.255 net_gateway


I would like this tool to be compatible with ovpn

**Comment by eebssk1** [comment]
> Hello, I also tried to link this tunnel with ovpn but it was not possible.
> 
> @thinkpeach-ho 
> @eebssk1 
> @fatedier 
> 
> 
> try
> serverAddr="216.189.154.18"
> serverPort = 80
> 
> [[proxies]]
> name = "ovpn"
> type = "tcp"
> localIP="127.0.0.1"
> localPort = 4545
> remotePort = 2323
> 
> 
> my configuration in ovpn is
> 
> remote 127.0.0.1 2323
> 
> route 216.189.154.18 255.255.255.255 net_gateway
> 
> 
> I also tried using http as a listener with socks5 and http in ovpn so that the tunnel connection was achieved and the connection was not made either.
> 
> socks-proxy 127.0.0.1 6004
> route 216.189.154.18 255.255.255.255 net_gateway
> 
> 
> socks-proxy 127.0.0.1 6003
> route 216.189.154.18 255.255.255.255 net_gateway
> 
> 
> I would like this tool to be compatible with ovpn
> 
> 
> 

OpenVPN uses UDP by default。

**Comment by testingnic** [comment]
@eebssk1 frpc and frps how should the configuration be?

And what port to use in the ovpn UDP client to make a connection, I tried it and still couldn't make a connection.

**Comment by testingnic** [comment]
??
