### ISSUE TITLE
Could we switch to xtaci/kcp-go and beego/beego?

### ISSUE THREAD

**Issue by yuzibo** [fatedier/frp#3907]
### Describe the feature request

Hi,
I am packaging the frp into Debian. But there are many packages which were not met.
So may I ask here, could we try to switch fatedier/beego and fatedier/kcp-go to  beego/beego&xtaci/kcp-go.
Debian sponsor refers to package the origin upstream than the vendor package. But I am not sure this will reduce your maintainance burden also, like https://github.com/fatedier/beego/pull/1 

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by fatedier** [comment]
Currently, there is no way to directly switch to the original upstream version. The main reason for using the forked version is that the upstream version is not stable enough. There have been unexpected bugs caused by updates in the past. I do not want to invest too much effort in third-party libraries, especially when the current version already fully meets the requirements. Another reason is the need for certain functionalities that the original repository's author may not be willing to support.

https://github.com/fatedier/beego/pull/1 The CVE being fixed here is something we have never used before. We only use the logging library from it and will not make frequent changes due to other content.

也许未来更好的方式是寻找替代的库，或是完全重写其中的部分内容，但不是现在。

**Comment by yuzibo** [comment]
Thanks for clarifying.
This is reason enough to convince them to use vendor libraries for the project.
btw, please feel free to close the issue if this is not on your plan or to-do list.:)

**Comment by yuzibo** [comment]
> #4009 The kcp-go package has been switched to the original upstream repository.

Oh, many thanks. This is really to reduce package work to Debian.
