### ISSUE TITLE
frpc客户端无法连接frps

### ISSUE THREAD

**Issue by dklinux** [fatedier/frp#432]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

0.9.3
**What operating system and processor architecture are you using (`go env`)?**
Centos 7.2

**Configures you used:**
frpc
[common]
server_addr = www.liudahome.f3322.net
server_port = 5443
privilege_token =
host_http_port = 8080

[ssh1]
type = http
custom_domains = test.liudahome.f3322.net
privilege_mode = true
use_gzip = true
use_encryption = true
local_port = 80
pool_count = 20

frps
[common]
bind_port = 5443
vhost_http_port = 16000
privilege_mode = true
privilege_token = 
privilege_allow_ports = 50-20000
max_pool_count = 100
dashboard_port = 6443
dashboard_user = admin
dashboard_pwd = 

**Steps to reproduce the issue:**
1.按照标准安装
2.frpc连接frps时报错
 [control.go:190] [E] ProxyName [ssh1], read from server error, read tcp 192.168.117.200:36524->47.93.17.110:5443: read: connection reset by peer
2017/08/20 02:18:40 [control.go:39] [E] ProxyName [ssh1], connect to server failed!

**Describe the results you received:**
无法连接frps 确认端口都已经放行了 VPS用的阿里云

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by qxwo** [comment]
D:\frp_0.13.0_windows_amd64>frpc.exe -c frpc.ini
2017/08/15 15:56:18 [W] [control.go:121] login to server failed: di
8.10.10:7000: connectex: A connection attempt failed because the co
did not properly respond after a period of time, or established co
ed because connected host has failed to respond.
dial tcp 192.168.10.10:7000: connectex: A connection attempt failed
connected party did not properly respond after a period of time, or  我的提示这个....也不行

**Comment by Nictheboy** [comment]
同样的情况，第一次连上了，之后就连不上了，怀疑是连接被阿里云或者运营商掐了
