### ISSUE TITLE
[Feature Request] is it possible to support multiple mqtt clients if its not already supported

### ISSUE THREAD

**Issue by Anzal-calixto** [fatedier/frp#4398]
### Describe the feature request

Now i am able to connect an mqtt gateway to the tunnel server but could not find any methods to support multiple clients. Similiar to connecting multiple ssh clients  

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [X] Security
- [ ] User Experience
- [X] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by JanzenJohn** [comment]
MQTT runs via TCP, this is already supported

**Comment by Anzal-calixto** [comment]
Hello @JanzenJohn  yes it is but i wasnt able to tunnel multiple connections using tcpmux

**Comment by JanzenJohn** [comment]
@Anzal-calixto 

This project proxies raw TCP/UDP connections. The content doesn't matter, but it won't provide tcpmux if that's your question.

I'm not that familiar with tcpmux, the [Wikipedia Page](https://en.m.wikipedia.org/wiki/TCP_Port_Service_Multiplexer) only told me it's been deprecated for ~8 Years.

Also the error description "it didn't work" isn't very helpful.

1. Please describe your Network configuration, and how frp fits in that configuration 

You can use a tool like paint to make this easier

2. Please explain your expected behavior
3. Please explain the actual behavior you encountered

When possible the error case should have real error messages attached.
