### ISSUE TITLE
proxy name [ssh] is already in use错误。

### ISSUE THREAD

**Issue by SuPerCxyz** [fatedier/frp#458]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**

**Steps to reproduce the issue:**
1.运行时显示proxy name [ssh] is already in use导致无法正常使用。
2.配置文件如下：
[common]
server_addr = xxxxx
server_port = 7000

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6001

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by sungda** [comment]
有别的设备运行过[ssh]命名的子项了并且没关闭frpc进程，换个名就行了，比如ssh1

**Comment by gouchaoer** [comment]
this is strange. if many people need to share a frp server, then the frpc.ini need a different config name.

**Comment by michalfapso** [comment]
you can use the `user = USERNAME` setting in the frpc.ini config file. Then, multiple users may have the same service name (e.g. `[ssh]`), because their proxy names would be:
- user1.ssh
- user2.ssh

This behavior is described in the [example frpc_full.ini](https://github.com/fatedier/frp/blob/3c2e2bcea55f6320d1720a42ce39bc3986291109/conf/frpc_full.ini#L50)

You can set the `user` parameter via an ENV variable (more info [here](https://github.com/fatedier/frp#using-environment-variables)), so you can have the same `frpc.ini` file on multiple computers. You just need to set an env variable which is unique for all those computers and use it for the `user` parameter in the `frpc.ini`.

**Comment by shaojun** [comment]
@michalfapso just don't like the design of using the section title: `[ssh]` as a unique key in server side for identify a client, as the `[ssh]` here is obvious a local descriptive info string, and the `remote_port` itself already proved the client's uniqueness.
