### ISSUE TITLE
[Doc]Comparison between frp and ssh port forwarding.

### ISSUE THREAD

**Issue by kawing-chiu** [fatedier/frp#818]
After reading the doc, I can find no information on the difference between frp and ssh port forwarding. Is frp more reliable/faster than ssh port forwarding? I think this is something that should appear in some "FAQ" section of the doc, because it's basic info that those who don't know much about frp may want to know.

Or even better, comparison against other alternative solutions/projects (ngrok etc.) can be added, too.

**Comment by fatedier** [comment]
Maybe no difference between frp and ssh port forwarding if you just need a port forwarding tool.
You can find all additional features from doc if you want more than a port forwarding tool.

**Comment by jasonmerc** [comment]
I don't mean to comment on a closed thread, but I have a related question.  SSH port forwarding tunnels your data through SSH, obviously, so that would mean there is a layer of encryption/protection on top of it.

Does FRP have any encryption or is it plaintext?  Or do we have to configure additional parameters to make it secure?  FRP is a great tool, I hope it can be secure over the wire as well.

**Comment by fatedier** [comment]
@jasonmerc https://github.com/fatedier/frp#encryption-and-compression
