### ISSUE TITLE
0.20版本dashboard 可以看到客户端ip吗

### ISSUE THREAD

**Issue by qingfengtaizi** [fatedier/frp#852]
0.20版本dashboard 可以看到客户端ip吗？如果不可以，我怎么样 才能监控到？谢谢各位大佬

**Comment by SeanDemo2017** [comment]
好像只可以看到端口 肖黎东‖Sean 职业：VFX特效师 Email：xiao940213@gmail.com TEL:+86 13066200549 Address:广东省江门市五邑大学 Postal Code:529020 QQ:204606460 Summary:后期特效师 视觉艺术家 https://www.seanvfx.com 签名由 网易邮箱大师 定制 在2018年07月16日 08:51，hermit 写道： 0.20版本dashboard 可以看到客户端ip吗？如果不可以，我怎么样 才能监控到？谢谢各位大佬 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by sshhsh** [comment]
日志里有，但是只有对应的公网ip

**Comment by BI7PRK** [comment]
+1
### 呼唤  dashboard 里能看到客户端的 Last IP

**Comment by fatedier** [comment]
没有计划支持。
