### ISSUE TITLE
使用境外VPS作为服务端连接路由器上的OpenVPN的问题

### ISSUE THREAD

**Issue by kid424** [fatedier/frp#853]
首先先感谢作者提供这么好用的工具，因为不是使用上的BUG类的问题，就不按照格式来了，如有不当之处请见谅。我使用境外VPS作为服务端，连接公司的虚拟机上的OpenVPN能够使用，但听说墙阻断OpenVPN的方式是流量特征，不知道这样使用会不会导致境外VPS的IP被墙？
顺便，我尝试过在NAT VPS上部署服务端，无法使用。服务端是否不支持NAT VPS？

**Comment by SeanDemo2017** [comment]
因为vpn协议容易被识别被墙，而且直接会被长城阻断，所以我一开始就用ss协议，建议用ss来链接吧 肖黎东‖Sean 职业：VFX特效师 Email：xiao940213@gmail.com TEL:+86 13066200549 Address:广东省江门市五邑大学 Postal Code:529020 QQ:204606460 Summary:后期特效师 视觉艺术家 https://www.seanvfx.com 签名由 网易邮箱大师 定制 在2018年07月16日 20:00，kid424 写道： 首先先感谢作者提供这么好用的工具，因为不是使用上的BUG类的问题，就不按照格式来了，如有不当之处请见谅。我使用境外VPS作为服务端，连接公司的虚拟机上的OpenVPN能够使用，但听说墙阻断OpenVPN的方式是流量特征，不知道这样使用会不会导致境外VPS的IP被墙？ 顺便，我尝试过在NAT VPS上部署服务端，无法使用。服务端是否不支持NAT VPS？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
