### ISSUE TITLE
请问一个小问题，frp转发中，vps的流量是不是双倍的？

### ISSUE THREAD

**Issue by bowenmail** [fatedier/frp#993]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

我的服务器是限流量的，如果我的中转服务器是B，那么从A上传100G的文件到C，轻过B中转。B的流量是不是200G？

**Comment by vanton** [comment]
上行100+下行100。

**Comment by SeanDemo2017** [comment]
vps一般按照出流量计费，一般请求流量很少（外网入vps，vps出到frpc），也就是最终流量是:vps download frpc内容，再出给外网，所以按理论，其中比不转发，消耗多的只是从vps再次向frpc请求的少量流量 肖黎东（守护星） 邮箱：xiao940213@gmail.com 签名由 网易邮箱大师 定制 在2018年12月08日 18:10，fatedier 写道： Closed #993. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
